name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme myst-parser
      - name: Sphinx build
        run: |
          echo "***********************************"
          echo `pwd`
          echo "***********************************"
          cd packages/pkg1 && sphinx-build -M html docs/source docs/build
          mv docs/build/html ../../docs
          echo "***********************************"
          echo `pwd`
          echo "***********************************"
          echo "***********************************"
          echo "cd ../../"
          cd ../../
          echo "***********************************"
          echo `pwd`
          echo "***********************************"
          ls *
          echo "***********************************"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.DOCS_REPO_PAT }}
          external_repository: fountaindive/not-data-docs
          #publish_branch: gh-pages
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true

