name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme myst-parser
      - name: Sphinx build
        run: |
          echo "testing"
          echo "***********************************"
          echo `pwd`
          echo "***********************************"


          echo "definine date directory"
          DATE_DIR=`date +%d%m%Y.%H%M%S`
          echo "DATE_DIR is ${DATE_DIR}"

          echo "making docs/docs/pkg1/${DATE_DIR}"
          mkdir -p docs/docs/pkg1/${DATE_DIR}

          echo "building docs"
          cd packages/pkg1 && sphinx-build -M html docs/source ${DATE_DIR}

          echo "moving docs to output"
          mv ${DATE_DIR}/html ../../docs/docs/pkg1/${DATE_DIR}
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.DOCS_REPO_PAT }}
          external_repository: fountaindive/not-data-docs
          #publish_branch: gh-pages
          publish_branch: main
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          force_orphan: true

